#!/bin/sh
#####################################################################################
# Just a kickstarter to launch the real app
#####################################################################################

# find the path where to execute tmm
PRG=$0
while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

progdir=`dirname "$PRG"`
cd "$progdir/../Resources/Java/"
exec `/bin/sh tinyMediaManagerOSX.sh`